output-format: pylint
strictness: veryhigh
autodetect: false

ignore-paths:
  - .mypy_cache
  - .pytest_cache
  - venv
  - __pycache__

mypy:
  run: false

bandit:
  run: true

dodgy:
  run: false

pylint:
  enable:
    - useless-suppression
  disable:
    - unused-argument
  options:
    max-line-length: 120
  load-plugins:
    - pylint_pydantic

pycodestyle:
  options:
    max-line-length: 120
  disable:
    - N805