output-format: pylint
strictness: veryhigh

ignore-paths:
  - .mypy_cache
  - venv
  - __pycache__

mypy:
  run: false

bandit:
  run: true

dodgy:
  run: false

pylint:
  enable:
    - useless-suppression
  disable:
    - invalid-name
    - unused-argument
  options:
    max-line-length: 120
    good-names: s

pep8:
  options:
    max-line-length: 120
  disable:
    - N803
    - N815